#!/bin/bash -e

# Single-worded command to - for now as of 3.20.16 at 7:14 am -
# update, upgrade, cleanup and "doctor" homebrew and brew cask.

if [[ ! -e /Users/$(logname)/git/myfunctions/allunix ]]; then
    sudo mkdir ~/git
    git clone https://github.com/jpartain89/myfunctions.git ~/git/myfunctions
fi

. /Users/$(logname)/git/myfunctions/allunix

brew_var () {
    echo ""
    echo "Brew Update"
    echo ""
    /usr/local/bin/brew update &&
    echo ""
    echo "Brew Upgrade"
    echo ""
    /usr/local/bin/brew upgrade &&
    echo ""
    echo "Brew Cleanup"
    echo ""
    /usr/local/bin/brew cleanup &&
    echo ""
    echo "Brew Prune"
    echo ""
    /usr/local/bin/brew prune &&
    echo ""
    echo "Brew Doctor"
    echo ""
    /usr/local/bin/brew doctor &&
    echo ""
    echo "Brew Cask Update"
    echo ""
    /usr/local/bin/brew cask update &&
    echo ""
    echo "Brew Cask Cleanup"
    echo ""
    /usr/local/bin/brew cask cleanup &&
    echo ""
    echo "Brew Cask Doctor"
    echo ""
    /usr/local/bin/brew cask doctor
}

help_text () {
cat <<- EOF
Usage: brewdate

This is a simple wrapper script that just auto-runs:

    brew update
    brew upgrade
    brew cleanup
    brew prune
    brew doctor
    brew cask update
    brew cask cleanup
        and
    brew cask doctor
EOF
}

trap help_text SIGHUP SIGINT SIGTERM

no_sudo; brew_var
