#!/bin/bash -e

# Calls ffmpeg to transcode from HEVC to MP4.
# Taken from http://askubuntu.com/a/707399
# see there for the full explainer

PROGNAME=$(basename "$0")

# setting filesystem variables depending on macOS or Linux
case $(uname) in
    Darwin)
        HOME_DIR="/Users/$(logname)"
        GIT_DIR="$HOME_DIR/git"
        ALLUNIX="$GIT_DIR/MyFunctions"
        if [[ ! -e "$ALLUNIX" ]]; then
            git clone https://jpartain89@github.com/jpartain89/allunix.git "$ALLUNIX"
        fi
        . "$ALLUNIX/allunix"
        ;;
    Linux)
        HOME_DIR="/home/$(logname)"
        GIT_DIR="$HOME_DIR/git"
        ALLUNIX="$GIT_DIR/MyFunctions"
        if [[ ! -e "$ALLUNIX" ]]; then
            git clone https://jpartain89@github.com/jpartain89/allunix.git "$ALLUNIX"
        fi
        . "$ALLUNIX/allunix"
    ;;
esac

install_ffmpeg () {

}

help_txt () {
cat <<- EOF
HEVCtoMP4

This is simply a wrapper shell script around ffmpeg to be able to
batch-transcode .mkv files into .mp4. Originally meant specifically for x265, I rather would transcode all the things to .mp4.

This program doesn\'t want any command line options included, only '-h' or '--help' are recognized. Anything else will show error output.
EOF
exit 1
}

clean_up () {
    sudo rm -r ./tmp_HEVC 2>/dev/null
    exit $1
}

error_txt () {
    echo "Sorry, ${PROGNAME} doesn't accept command line options."
    echo "Please, use -h or --help for more info."
    exit 1
    clean_up
}

trap clean_up SIGHUP SIGINT SIGTERM

if [[ $# -eq 1 ]] && ( [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] ); then
    if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
        help_text
    fi
    error_txt
fi

for mkv_file in ./*.mkv; do
    if [[ ! -f "${mkv_file}" ]]; then
        echo ""
        echo "There's no .mkv files here.... Exiting!"
        clean_up
    else
        mkv_default=${1:-*.mkv}
        break
    fi
done

while [[ "$(ls ./*.mkv)" != "" ]]; do
    for i in  $mkv_default; do
        ffmpeg -i "$i" -bsf:v h264_mp4toannexb -vcodec libx264 "./tmp_HEVC/$i.ts"
        mv "./tmp_HEVC/$i.ts" "$i.mp4"
    done

clean_up "$@"
