#!/bin/bash -e

# Convert x265/HEVC mkv video files to mp4's
# Taken from http://askubuntu.com/a/707399
# see there for the full explainer

# For now, the quick and dirty way, not even OS testing.

# sourcing myfunctions file
. /Users/$(logname)/git/myfunctions/allunix

install_ffmpeg () {
    if [[ "$(which ffmpeg)" == "" ]]; then
        echo "Installing ffmpeg"
        /usr/local/bin/brew install ffmpeg
    fi
}

while [[ $# -ge 1 ]]; do
    if [[ $# == "*.mkv" ]]; then
        echo "Sorry, don't know how to test for x265 codec yet."
        echo "Make sure you check that info in Subler, please."
        for i in  $1; do
            ffmpeg -i "$i" -bsf:v h264_mp4toannexb -vcodec libx264 "$i.ts"
            mv "$i.ts" "$i.mp4"
        done
    else
        echo "Sorry, but the file you have on the terminal line isn't an .mkv file"
        echo "Please, try again."
        exit 1
    fi
    if [[ $2 != "" ]]; then
        shift
    else
        exit 0
    fi
done
