#!/bin/bash -e

# This wrapper script is specifically for running chmod on either ONLY files
# or ONLY directories. It requires listing a flag to differentiate between
# files and directories and another entry for the chmod numbers.
# There is a default chmod number for both files and directories:
#
# files:       0644 - or - "-rw-r--r--" user `rw`;  group and other `r`
# directories: 0775 - or - "drwxrw-r-x" user `rwx`;  group `rw` and other `r`

# Forcing sudo
if [[ $EUID != 0 ]]; then
    echo ""
    echo "Sorry, but you have to use sudo."
    echo ""
    exit 1
fi

# Setting default chmod values
FILE_FLAG=0644
DIR_FLAG=0775

# Set default maxdepth value, especially helpful if ever allowing user input for this
#MAXDEPTH=" -maxdepth 0"

WORKDIR=$(pwd)
echo $WORKDIR

while [[ $# -ge 1 ]]; do
    case $1 in
    file)
        if [[ $# -gt 1 ]]; then
            echo "Running CHMOD with $2"
            find "$WORKDIR" -type f -maxdepth 1 -exec chmod $2 {} \;
            exit 0
        else
            echo "Running CHMOD with $FILE_FLAG"
            find "$WORKDIR" -type f -maxdepth 1 -exec chmod $FILE_FLAG {} \;
            exit 0
        fi
        ;;
    dir|directory)
        if [[ $# -gt 1 ]]; then
            echo "Running CHMOD with $2"
            find "$WORKDIR" -type d -maxdepth 1 -exec chmod $2 {} \;
            exit 0
        else
            echo "Running CHMOD with $DIR_FLAG"
            find "$WORKDIR" -type d -maxdepth 1 -exec chmod $DIR_FLAG {} \;
            exit 0
        fi
        ;;
    *)
        help_text
        exit 1
        ;;
    esac
done

help_text () {
cat <<- EOF
jp-chmod

Quick way to change all of the FILES or DIRECTORIES on the same directory level
as the program was called in.

jp-chmod [file | dir, directory] [ chmod numbers/letters - not required]

Options:

    file:               : Signifies you want the files in the current working
                          directory updated
    dir | directory:    : Signifies you want the directories in the current
                          working directory updated

Optional Option:

    The second field after [file | dir] is an optional field, meant for the
    CHMOD information. Can be either numbers or letters. If not input, will
    default to:
        0644 for Files
        0775 for Directories
EOF
}
