#!/bin/bash -e

# This is my OS Detecting script to have sourced by other scripts.

case $(uname) in

    # mac
    Darwin )
        OS="macOS"
        HOME_DIR="/Users"
        GIT_DIR="$HOME_DIR/git"
        DOT_LOC="$GIT_DIR/macos_dotfiles"
        FIRST_STEPS="$GIT_DIR/unix-first-steps"
        if [ -x /usr/bin/sw_vers ]; then
            OS_NAME=$(/usr/bin/sw_vers -productName)
            OS_VERSION=$(/usr/bin/sw_vers -productVersion)
            case ${OS_VERSION} in
                10.9 | 10.9.[0-9]* )
                    OS_VERSION_NAME="Mavericks"
                    OS_FULLNAME="Mac OS X 10.9  (${OS_VERSION_NAME})" ;;
                10.10 | 10.10.[0-9]* )
                    OS_VERSION_NAME="Yosemite"
                    OS_FULLNAME="Mac OS X 10.10 (${OS_VERSION_NAME}" ;;
                10.11 | 10.11.[0-9]* )
                    OS_VERSION_NAME="El Capitan"
                    OS_FULLNAME="Mac OS X 10.11 (${OS_VERSION_NAME})" ;;
                10.12 | 10.12.[0-9]* )
                    OS_VERSION_NAME="Sierra"
                    OS_FULLNAME="macOS ${OS_VERSION_NAME} (${OS_VERSION})" ;;
                * ) echo "Unknown macOS/Mac OS X version." ;;
            esac
        else
            # Fall back to fairly safe names
            OS_NAME="macOS"
            OS_VERSION=$(/usr/bin/sw_vers -productVersion)
            OS_FULLNAME="${OS_NAME} ${OS_VERSION}"
        fi ;;
    Linux )
        OS="Linux"
        OS_NAME="Linux"
        OS_FULLNAME=""
        OS_VERSION=$(uname -r)
        LINUX_VERSION=""
        HARDWARE=$(uname -m)
        HOME_DIR="/home"
        GIT_DIR="$HOME_DIR/git"
        DOT_LOC="$GIT_DIR/linux_dotfiles"
        FIRST_STEPS="$GIT_DIR/unix-first-steps"
        if [[ -e /etc/os-release ]]; then
            OS_ID=$(grep "^ID=" /etc/os-release | awk -F= '{print $2}')
            if [[ ! -z "${OS_ID}" ]]; then
                case ${OS_ID} in
                    "ubuntu" )
                        LINUX_VERSION="Ubuntu"
                        OS_FULLNAME=$(grep "^PRETTY_NAME=" /etc/os-release | awk -F= '{print $2}' | tr -d '"')
                        OS_VERSION=$(grep "^VERSION_ID=" /etc/os-release | awk -F= '{print $2}' | tr -d '"')
                        OS_NAME="Ubuntu Linux"
                    ;;
                    * )
                        echo "Unknown OS found in /etc/os-release." ;;
                esac
            fi
        fi
    esac
